jobs:
- job: sync_files
  displayName: 'Sync Files from Azure Storage'
  pool:
    vmImage: 'windows-latest'

  steps:
    # STEP 1: Checkout Source Code
    # Checks out the repository's source code.
    - checkout: self
      persistCredentials: true
      fetchDepth: 0

    # STEP 2: Configure Git
    # Sets up global Git user email and name for commit operations.
    - task: PowerShell@2
      displayName: 'Configure Git'
      inputs:
        targetType: 'inline'
        script: |
          git config --global user.email "automation@gmail.com"
          git config --global user.name "automation"

    # STEP 3: Install AzCopy
    # Downloads, extracts, and sets the path to the AzCopy executable.
    - task: PowerShell@2
      displayName: 'Install AzCopy'
      inputs:
        targetType: 'inline'
        script: |
          $azcopyPath = Join-Path "$(Agent.TempDirectory)" "azcopy"
          New-Item -ItemType Directory -Path $azcopyPath -Force
          $zipFile = Join-Path $azcopyPath "azcopy.zip"
          Invoke-WebRequest -Uri https://aka.ms/downloadazcopy-v10-windows -OutFile $zipFile
          Expand-Archive $zipFile -DestinationPath $azcopyPath -Force
          $azcopyExe = Get-ChildItem -Path $azcopyPath -Recurse -Filter "azcopy.exe" | Select-Object -First 1
          echo "##vso[task.setvariable variable=AZCOPY_EXE]$($azcopyExe.FullName)"

    # STEP 4: Sync Files from Azure Blob Storage
    # Authenticates AzCopy using Azure CLI credentials and performs the sync operation.
    - task: AzureCLI@2
      displayName: 'Sync Files to ADLS_Backup_Folder'
      inputs:
        azureSubscription: 'Virtualize Health(726fbb03-a12a-4620-b068-0c0fe0629c1b)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $ErrorActionPreference = "Stop"

          Write-Host "Attempting AzCopy login using Azure CLI's managed identity..."
          try {
              # Try AzCopy's built-in identity login first
              & "$(AZCOPY_EXE)" login --identity | Write-Host
          } catch {
              # If --identity fails, fall back to getting the token directly from Azure CLI
              Write-Warning "AzCopy login --identity failed. Trying to get token from Azure CLI..."

              $accessToken = az account get-access-token --resource-type=storage --query accessToken --output tsv
              if ([string]::IsNullOrEmpty($accessToken)) {
                  throw "Failed to retrieve access token from Azure CLI."
              }
              Write-Host "Successfully retrieved access token. Setting AZCOPY_OAUTH_TOKEN."
              $env:AZCOPY_OAUTH_TOKEN = $accessToken
          }

          # Parse the source folder name from the container URL
          $uri = [System.Uri]"$(containerUrl)"
          $sourceFolderName = $uri.AbsolutePath.TrimEnd('/').Split('/')[-1]
          Write-Host "Determined source folder name to be: $sourceFolderName"

          # Construct the full destination path
          $parentFolderPath = Join-Path "$(Build.SourcesDirectory)" "$(targetFolderName)"
          $syncDestinationPath = Join-Path -Path $parentFolderPath -ChildPath $sourceFolderName

          # Ensure the destination directory exists
          New-Item -ItemType Directory -Path $parentFolderPath -Force

          Write-Host "Syncing files from container to $syncDestinationPath"
          # Execute AzCopy sync. It will use the authentication established above.
          & "$(AZCOPY_EXE)" sync "$(containerUrl)" $syncDestinationPath --recursive --delete-destination=true

          # Good practice: Clear the sensitive environment variable after use
          if ($env:AZCOPY_OAUTH_TOKEN) {
              Remove-Item Env:AZCOPY_OAUTH_TOKEN -ErrorAction SilentlyContinue
              Write-Host "AZCOPY_OAUTH_TOKEN environment variable cleared."
          }

          Write-Host "AzCopy command completed."

    # STEP 5: Commit and Push Updates
    # Commits any changes made by the sync operation and pushes them to the 'main' branch.
    - task: PowerShell@2
      displayName: 'Commit and Push Updates to main'
      inputs:
        targetType: 'inline'
        script: |
          $ErrorActionPreference = "Stop"
          git checkout main
          git pull origin main
          Set-Location "$(Build.SourcesDirectory)"
          git add -A
          # Check if there are any pending changes to commit
          if (-not (git diff-index --quiet HEAD --)) {
            Write-Host "Changes detected in $(targetFolderName). Committing to main..."
            git commit -m "Weekly sync of ADLS backup folder - $env:BUILD_BUILDID"
            Write-Host "Pushing changes to origin/main..."
            git push origin main
          } else {
            Write-Host "No changes detected. Nothing to commit."
          }