trigger: none  # No CI trigger

schedules:
  - cron: "0 14 * * 1"  # Every Monday at 10 AM ET
    displayName: Weekly Sync
    branches:
      include:
        - main
    always: true

variables:
  containerUrl: 'https://vhdcomstor01.blob.core.windows.net/commons-prod'
  syncFolder: '$(Build.SourcesDirectory)/synced-files'
  backupPrefix: 'backup'

jobs:
- job: sync_and_backup
  displayName: Sync Azure Blob and Backup GitHub
  pool:
    vmImage: 'windows-latest'

  steps:
    - checkout: self
      persistCredentials: true

    - task: PowerShell@2
      displayName: 'Install AzCopy'
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest -Uri https://aka.ms/downloadazcopy-v10-windows -OutFile azcopy.zip
          Expand-Archive azcopy.zip -DestinationPath . -Force
          $azCopyPath = Get-ChildItem -Recurse -Filter "azcopy.exe" | Select-Object -First 1
          echo "##vso[task.setvariable variable=AZCOPY_EXE]$($azCopyPath.FullName)"

    - task: AzureCLI@2
      displayName: 'Sync Blobs (with deletes) into Repo Subfolder'
      inputs:
        azureSubscription: 'Virtualize Health(726fbb03-a12a-4620-b068-0c0fe0629c1b)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $ErrorActionPreference = "Stop"
          mkdir "$(syncFolder)" -Force
          & "$(AZCOPY_EXE)" sync "$(containerUrl)" "$(syncFolder)" --recursive --delete-destination=true

    - task: PowerShell@2
      displayName: 'Always Commit and Push to Main'
      inputs:
        targetType: 'inline'
        script: |
          git config --global user.email "gabriel@virtualizehealth.com"
          git config --global user.name "virtualizehealth"

          Set-Location "$(Build.SourcesDirectory)"
          if (-not (Test-Path ".git")) {
            Write-Error ".git folder not found. Make sure you're in a Git repo."
            exit 1
          }

          git checkout main
          Copy-Item -Path "$(syncFolder)\*" -Destination "$(Build.SourcesDirectory)" -Recurse -Force
          git add -A
          git commit -m "Weekly sync from Azure Blob - $env:BUILD_BUILDID" --allow-empty
          git push origin main

    - task: PowerShell@2
      displayName: 'Create Backup Snapshot Branch'
      inputs:
        targetType: 'inline'
        script: |
          $ErrorActionPreference = "Stop"
          cd "$(Build.SourcesDirectory)"

          $oldBranch = "main"
          $dtNow = Get-Date -UFormat "%Y-%m-%d"
          $branchPrefix = "$(backupPrefix)/$dtNow"
          $repoList = git branch -r
          $suffix = [int][char]"A"

          $repoList.Split("`n") | ForEach-Object {
            $line = $_.Trim()
            if ($line.StartsWith("origin/" + $branchPrefix)) {
              $testSuffix = [int][char]($line.Substring($branchPrefix.Length + 7))
              if ($testSuffix -ge $suffix) { $suffix = $testSuffix + 1 }
            }
          }

          $newBranch = "$branchPrefix" + [char]$suffix
          git checkout -b $newBranch
          git push -u origin $newBranch

          $repoList.Split("`n") | Where-Object { $_.Trim().StartsWith("origin/$(backupPrefix)/") } | ForEach-Object {
            $branchToDelete = $_.Trim().Substring(7)
            if ($branchToDelete -ne $newBranch) {
              Write-Host "Deleting old branch: $branchToDelete"
              git push origin --delete $branchToDelete
            }
          }

          git checkout $oldBranch