# =========================================================================================
# PIPELINE TRIGGER AND SCHEDULE CONFIGURATION
# This pipeline runs every Monday at 14:00 UTC (10 AM ET) to sync files.
# =========================================================================================
trigger: none

schedules:
  - cron: "0 14 * * 1"
    displayName: Weekly Sync
    branches:
      include:
        - main
    always: true

# =========================================================================================
# PIPELINE VARIABLES
# These variables define key paths for syncing files.
# =========================================================================================
variables:
  containerUrl: 'https://vhdcomstor01.blob.core.windows.net/commons-prod/blob_file_folder2/'
  targetFolderName: 'ADLS_Backup_Folder'

# =========================================================================================
# JOB DEFINITION
# Defines the job for syncing files from Azure Blob Storage.
# =========================================================================================
jobs:
- job: sync_files
  displayName: 'Sync Files from Azure Storage'
  pool:
    vmImage: 'windows-latest'

  steps:
    # STEP 1: Checkout Source Code
    # Checks out the repository's source code.
    - checkout: self
      persistCredentials: true
      fetchDepth: 0

    # STEP 2: Configure Git
    # Sets up global Git user email and name for commit operations.
    - task: PowerShell@2
      displayName: 'Configure Git'
      inputs:
        targetType: 'inline'
        script: |
          git config --global user.email "automation@gmail.com"
          git config --global user.name "automation"

    # STEP 3: Install AzCopy
    # Downloads, extracts, and sets the path to the AzCopy executable.
    - task: PowerShell@2
      displayName: 'Install AzCopy'
      inputs:
        targetType: 'inline'
        script: |
          $azcopyPath = Join-Path "$(Agent.TempDirectory)" "azcopy"
          New-Item -ItemType Directory -Path $azcopyPath -Force
          $zipFile = Join-Path $azcopyPath "azcopy.zip"
          Invoke-WebRequest -Uri https://aka.ms/downloadazcopy-v10-windows -OutFile $zipFile
          Expand-Archive $zipFile -DestinationPath $azcopyPath -Force
          $azcopyExe = Get-ChildItem -Path $azcopyPath -Recurse -Filter "azcopy.exe" | Select-Object -First 1
          echo "##vso[task.setvariable variable=AZCOPY_EXE]$($azcopyExe.FullName)"

    # STEP 4: Sync Files from Azure Blob Storage
    # Configures AzCopy to use Azure CLI credentials and performs the sync operation.
    - task: AzureCLI@2
      displayName: 'Sync Files to ADLS_Backup_Folder'
      inputs:
        azureSubscription: 'Virtualize Health(726fbb03-a12a-4620-b068-0c0fe0629c1b)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $ErrorActionPreference = "Stop"

          Write-Host "Setting AZCOPY_AUTO_LOGIN_TYPE to AZCLI..."
          $env:AZCOPY_AUTO_LOGIN_TYPE="AZCLI"

          # The AzureCLI@2 task inherently logs in to Azure CLI using the 'azureSubscription' service connection.
          # We can optionally run 'az account show' to verify login, though it's not strictly necessary for AzCopy to work.
          Write-Host "Verifying Azure CLI login..."
          az account show | Out-Host

          $uri = [System.Uri]"$(containerUrl)"
          $sourceFolderName = $uri.AbsolutePath.TrimEnd('/').Split('/')[-1]
          Write-Host "Determined source folder name to be: $sourceFolderName"

          $parentFolderPath = Join-Path "$(Build.SourcesDirectory)" "$(targetFolderName)"
          $syncDestinationPath = Join-Path -Path $parentFolderPath -ChildPath $sourceFolderName

          New-Item -ItemType Directory -Path $parentFolderPath -Force

          Write-Host "Syncing files from container to $syncDestinationPath"
          # AzCopy will now automatically use the Azure CLI credentials because AZCOPY_AUTO_LOGIN_TYPE is set.
          & "$(AZCOPY_EXE)" sync "$(containerUrl)" $syncDestinationPath --recursive --delete-destination=true

          Write-Host "AzCopy command completed."

          # Clean up the environment variable if you wish, though it's typically scoped to the task.
          # Remove-Item Env:AZCOPY_AUTO_LOGIN_TYPE -ErrorAction SilentlyContinue

    # STEP 5: Commit and Push Updates
    # Commits any changes made by the sync operation and pushes them to the 'main' branch.
    - task: PowerShell@2
      displayName: 'Commit and Push Updates to main'
      inputs:
        targetType: 'inline'
        script: |
          $ErrorActionPreference = "Stop"
          git checkout main
          git pull origin main
          Set-Location "$(Build.SourcesDirectory)"
          git add -A
          # Check if there are any pending changes to commit
          if (-not (git diff-index --quiet HEAD --)) {
            Write-Host "Changes detected in $(targetFolderName). Committing to main..."
            git commit -m "Weekly sync of ADLS backup folder - $env:BUILD_BUILDID"
            Write-Host "Pushing changes to origin/main..."
            git push origin main
          } else {
            Write-Host "No changes detected. Nothing to commit."
          }