trigger: none

schedules:
  - cron: "0 14 * * 1" # Every Monday at 10 AM ET
    displayName: Weekly Sync
    branches:
      include:
        - main
    always: true

variables:
  containerUrl: 'https://vhdcomstor01.blob.core.windows.net/commons-prod'
  # NEW: Define the final destination folder name
  targetFolderName: 'ADLS_Backup_Folder'
  backupPrefix: 'backup'

jobs:
- job: sync_and_backup
  displayName: 'Backup, Sync, and Prune'
  pool:
    vmImage: 'windows-latest'

  steps:
    - checkout: self
      persistCredentials: true
      fetchDepth: 0

    - task: PowerShell@2
      displayName: 'Configure Git'
      inputs:
        targetType: 'inline'
        script: |
          git config --global user.email "gabriel@virtualizehealth.com"
          git config --global user.name "virtualizehealth"

    # This task is unchanged. It correctly creates a snapshot of `main` before any updates.
    - task: PowerShell@2
      displayName: 'Create Backup Branch from Previous State'
      inputs:
        targetType: 'inline'
        script: |
          $ErrorActionPreference = "Stop"
          Write-Host "Switching to the main branch to create a pre-update backup..."
          git checkout main
          git pull origin main
          $dtNow = Get-Date -UFormat "%Y-%m-%d"
          $branchPrefix = "$(backupPrefix)/$dtNow"
          $repoList = git branch -r
          $suffix = [int][char]"A"
          $repoList.Split("`n") | ForEach-Object {
            $line = $_.Trim()
            if ($line.StartsWith("origin/" + $branchPrefix)) {
              $testSuffix = [int][char]($line.Substring($branchPrefix.Length + 7))
              if ($testSuffix -ge $suffix) { $suffix = $testSuffix + 1 }
            }
          }
          $newBranch = "$branchPrefix" + [char]$suffix
          Write-Host "Creating new backup branch: $newBranch"
          git checkout -b $newBranch
          git push -u origin $newBranch
          echo "##vso[task.setvariable variable=newBackupBranch]$newBranch"
          Write-Host "Backup created. Switching back to main to apply updates."
          git checkout main

    - task: PowerShell@2
      displayName: 'Install AzCopy to Temp Directory'
      inputs:
        targetType: 'inline'
        script: |
          $azcopyPath = Join-Path -Path "$(Agent.TempDirectory)" -ChildPath "azcopy"
          New-Item -ItemType Directory -Path $azcopyPath -Force
          $zipFile = Join-Path $azcopyPath "azcopy.zip"
          Invoke-WebRequest -Uri https://aka.ms/downloadazcopy-v10-windows -OutFile $zipFile
          Expand-Archive $zipFile -DestinationPath $azcopyPath -Force
          $azcopyExe = Get-ChildItem -Path $azcopyPath -Recurse -Filter "azcopy.exe" | Select-Object -First 1
          echo "##vso[task.setvariable variable=AZCOPY_EXE]$($azcopyExe.FullName)"

    # MODIFIED: This task now syncs directly to the target folder.
    - task: AzureCLI@2
      displayName: 'Sync Blobs to ADLS_Backup_Folder'
      inputs:
        azureSubscription: 'Virtualize Health(726fbb03-a12a-4620-b068-0c0fe0629c1b)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $ErrorActionPreference = "Stop"
          # Path to the final destination folder in the repo
          $targetFolderPath = Join-Path -Path "$(Build.SourcesDirectory)" -ChildPath "$(targetFolderName)"
          Write-Host "Syncing files from container to $targetFolderPath"
          New-Item -ItemType Directory -Path $targetFolderPath -Force
          
          # Sync directly into the target folder, deleting any files that no longer exist in the source
          & "$(AZCOPY_EXE)" sync "$(containerUrl)" $targetFolderPath --recursive --delete-destination=true

    # MODIFIED: This task is now simpler, as files are already in the correct location.
    - task: PowerShell@2
      displayName: 'Commit and Push Updates to main'
      inputs:
        targetType: 'inline'
        script: |
          $ErrorActionPreference = "Stop"
          Set-Location "$(Build.SourcesDirectory)"
          
          # The files are already in ADLS_Backup_Folder. We just need to stage the changes.
          git add -A

          if (-not (git diff-index --quiet HEAD --)) {
            Write-Host "Changes detected in $(targetFolderName). Committing to main..."
            git commit -m "Weekly sync of ADLS backup folder - $env:BUILD_BUILDID"
            Write-Host "Pushing changes to origin/main..."
            git push origin main
          } else {
            Write-Host "No changes detected. Nothing to commit."
          }

    # This task is unchanged. It cleans up old backup branches.
    - task: PowerShell@2
      displayName: 'Prune Old Backup Branches'
      inputs:
        targetType: 'inline'
        script: |
          $ErrorActionPreference = "Stop"
          $newBranchToKeep = "$(newBackupBranch)"
          Write-Host "Keeping new backup branch: $newBranchToKeep"
          git branch -r | Where-Object { $_.Trim().StartsWith("origin/$(backupPrefix)/") } | ForEach-Object {
            $branchToDelete = $_.Trim().Substring(7)
            if ($branchToDelete -ne $newBranchToKeep) {
              Write-Host "Deleting old backup branch: $branchToDelete"
              git push origin --delete $branchToDelete
            }
          }