# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Does this update show up?

trigger: none  # no CI trigger

schedules:
  - cron: "0 14 * * 1"  # every Monday at 10 AM ET
    displayName: Weekly Sync
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  containerUrl: "https://vhdcomstor01.blob.core.windows.net/commons-prod"
  repoFolder: "$(Build.SourcesDirectory)/main"

steps:
  - script: |
      git clone https://$(GitHubPAT)@github.com/your-org/your-repo.git
    displayName: 'Clone GitHub Repo'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Virtualize Health(726fbb03-a12a-4620-b068-0c0fe0629c1b)'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        azcopy copy "$(containerUrl)/*" "$(repoFolder)/" --recursive
    displayName: 'Copy Blobs into Repo'

  - script: |
      cd $(repoFolder)
      git add .
      if git diff --cached --quiet; then
        echo "No changes to commit."
      else
        git commit -m "Weekly sync from Azure Blob - $(Build.BuildId)"
        git push origin main
      fi
    displayName: 'Commit & Push if Changed'